import sys
sys.path.append('../')
from local_align import disjointAlignments as DA
from local_align import localAlign as LA

""" 
Test File for local_align module
""" 

"""
Tests for localAlign class
"""

"""
Tests provided with assignment 2 
(Uses Protein sequences)
"""

# OSXR1_HUMAN in uniprot data
seq1 = ("MSEDSSALPWSINRDDYELQEVIGSGATAVVQAAYCAPKKEKVAIKRINLEKCQTSMDEL"
	"LKEIQAMSQCHHPNIVSYYTSFVVKDELWLVMKLLSGGSVLDIIKHIVAKGEHKSGVLDE"
	"STIATILREVLEGLEYLHKNGQIHRDVKAGNILLGEDGSVQIADFGVSAFLATGGDITRN"
	"KVRKTFVGTPCWMAPEVMEQVRGYDFKADIWSFGITAIELATGAAPYHKYPPMKVLMLTL"
	"QNDPPSLETGVQDKEMLKKYGKSFRKMISLCLQKDPEKRPTAAELLRHKFFQKAKNKEFL"
	"QEKTLQRAPTISERAKKVRRVPGSSGRLHKTEDGGWEWSDDEFDEESEEGKAAISQLRSP"
	"RVKESISNSELFPTTDPVGTLLQVPEQISAHLPQPAGQIATQPTQVSLPPTAEPAKTAQA"
	"LSSGSGSQETKIPISLVLRLRNSKKELNDIRFEFTPGRDTAEGVSQELISAGLVDGRDLV"
	"IVAANLQKIVEEPQSNRSVTFKLASGVEGSDIPDDGKLIGFAQLSIS")

# NEK3_HUMAN
seq2 = ("MDDYMVLRMIGEGSFGRALLVQHESSNQMFAMKEIRLPKSFSNTQNSRKEAVLLAKMKHP"
	"NIVAFKESFEAEGHLYIVMEYCDGGDLMQKIKQQKGKLFPEDMILNWFTQMCLGVNHIHK"
	"KRVLHRDIKSKNIFLTQNGKVKLGDFGSARLLSNPMAFACTYVGTPYYVPPEIWENLPYN"
	"NKSDIWSLGCILYELCTLKHPFQANSWKNLILKVCQGCISPLPSHYSYELQFLVKQMFKR"
	"NPSHRPSATTLLSRGIVARLVQKCLPPEIIMEYGEEVLEEIKNSKHNTPRKKTNPSRIRI"
	"ALGNEASTVQEEEQDRKGSHTDLESINENLVESALRRVNREEKGNKSVHLRKASSPNLHR"
	"RQWEKNVPNTALTALENASILTSSLTAEDDRGGSVIKYSKNTTRKQWLKETPDTLLNILK"
	"NADLSLAFQTYTIYRPGSEGFLKGPLSEETEASDSVDGGHDSVILDPERLEPGLDEEDTD"
	"FEEEDDNPDWVSELKKRAGWQGLCDR")

align = LA(seq1, seq2)
align.computeAlignment()
LA.printAlignment(align.align_info)

seq2 = ("MSLCGARANAKMMAAYNGGTSAAAAGHHHHHHHHLPHLPPPHLHHHHHPQHHLHPGSAAA"
	"VHPVQQHTSSAAAAAAAAAAAAAMLNPGQQQPYFPSPAPGQAPGPAAAAPAQVQAAAAAT"
	"VKAHHHQHSHHPQQQLDIEPDRPIGYGAFGVVWSVTDPRDGKRVALKKMPNVFQNLVSCK"
	"RVFRELKMLCFFKHDNVLSALDILQPPHIDYFEEIYVVTELMQSDLHKIIVSPQPLSSDH"
	"VKVFLYQILRGLKYLHSAGILHRDIKPGNLLVNSNCVLKICDFGLARVEELDESRHMTQE"
	"VVTQYYRAPEILMGSRHYSNAIDIWSVGCIFAELLGRRILFQAQSPIQQLDLITDLLGTP"
	"SLEAMRTACEGAKAHILRGPHKQPSLPVLYTLSSQATHEAVHLLCRMLVFDPSKRISAKD"
	"ALAHPYLDEGRLRYHTCMCKCCFSTSTGRVYTSDFEPVTNPKFDDTFEKNLSSVRQVKEI"
	"IHQFILEQQKGNRVPLCINPQSAAFKSFISSTVAQPSEMPPSPLVWE")

align = LA(seq1, seq2)
align.computeAlignment()
LA.printAlignment(align.align_info)


"""
Tests for DisjointAlignment Class
"""

""" 
Perfect matches
"""
seq1 = "AAAARRRRNNNNNDDDDDD"
seq2 = "AAAARRRRNNNNNDDDDDD"

align = DA(seq1, seq2)
align.kAlignments(1)
align.printAlignments()


"""
Matches with gaps
"""
seq1 = "AAAADDDDDDRRRRDDDDDNNNNNFFFFFFDDDDDD"
seq2 = "AAAAFFFFFFRRRRFFFFFNNNNNDDDDDDDDDDDD"
align = DA(seq1, seq2)
align.kAlignments(4)
align.printAlignments()



